### ISSUE TITLE
Deploy to cloud server

### ISSUE THREAD

**Issue by spheregenomics** [misshie/docker-ucsc-blat#1]
A question: is it possible to deploy these containers to a cloud server Ubuntu VM, eg: Google or Amazon?

**Comment by misshie** [comment]
Thank you for your question. I have not used cloud services of Amazon and Google. The UCSC-BLAT containers contain relatively large 2bit files (hg19 or hg38, about 800M bytes) inside. I think they work if cloud environment has enough resource (storage/memory) to load them.

**Comment by spheregenomics** [comment]
Thank you
